shellfie:
  image: maxwo/shellfie:latest
  labels:
    SERVICE_TAGS: traefik.frontend.rule=PathPrefixStrip:/shellfie
    SERVICE_80_CHECK_HTTP: /
    traefik.frontend.rule: PathPrefixStrip:/shellfie
    traefik.enabled: true
