version: '2'

services:
  node:
    image: maxwo/hazelcast-rancher
    labels:
      io.rancher.container.pull_image: 'always'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
