version: '2'
services:
  agent:
    image: consul:latest
    hostname: consul-agent
    ports:
    - 8400:8400/tcp
    - 8500:8500/tcp
    - 8600:53/tcp
    expose:
    - '8400'
    - '8500'
    - '8600'
    command:
    - -ui-dir=/ui
    - -retry-join=consul1
    - -client=0.0.0.0
    - -bind=0.0.0.0
  server:
    image: consul:latest
    hostname: consul1
    command:
    - -server
    - -bootstrap-expect=3
    - -ui-dir=/ui
    - -join=server-1
