healthcheck:
  image: maxwo/healthcheck:latest
  labels:
    SERVICE_TAGS: traefik.frontend.rule=PathPrefixStrip:/healthcheck
    SERVICE_8080_CHECK_HTTP: /healthcheck
    traefik.frontend.rule: PathPrefixStrip:/healthcheck
