name: Healthcheck
description: |
  A dummy project implementing a health check for testing purposes.
version: 0.6-rancher2
category: Testing
maintainer: Maxime Wojtczak
license: MIT
projectURL: https://github.com/maxwo/healthcheck
