version: '2'

services:
  agent:
    image: consul:latest
    ports:
    - 8500:8500/tcp
    command:
    - agent
    - -ui
    - -retry-join=consul-server-1
    - -retry-join=consul-server-2
    - -retry-join=consul-server-3
    - -client=0.0.0.0
    - -bind=0.0.0.0

  server:
    image: consul:latest
    command:
    - agent
    - -server
    - -bootstrap-expect=3
    - -retry-join=consul-server-1
    - -retry-join=consul-server-2
    - -retry-join=consul-server-3
