version: '2'

services:
  agent:
    image: consul:0.8.0
    ports:
    - 8500:8500/tcp
    command:
    - agent
    - -ui
    - -retry-join=consul-server-1
    - -retry-join=consul-server-2
    - -retry-join=consul-server-3
    - -disable-host-node-id
    - -client=0.0.0.0
    - -bind=0.0.0.0
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.pull_image: 'always'

  server:
    image: consul:0.8.0
    command:
    - agent
    - -server
    - -bootstrap-expect=3
    - -retry-join=consul-server-1
    - -retry-join=consul-server-2
    - -retry-join=consul-server-3
    - -client=0.0.0.0
    - -disable-host-node-id
    labels:
      io.rancher.container.pull_image: 'always'
