version: '2'

catalog:
  name: "Consul"
  description: "Service discovery by Hashicorp."
  version: "0.8.0"
  uuid: consul

services:
  agent:
    scale: 1
    start_on_create: true
  server:
    scale: 3
    start_on_create: true
